"""add audit_events + forward_inbox_address

Revision ID: 0e0fda40cb5f
Revises: d34018629af0
Create Date: 2026-04-25 15:35:06.684638
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e0fda40cb5f'
down_revision: Union[str, None] = 'd34018629af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forward_inbox_address', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.drop_column('forward_inbox_address')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
