"""add webhook_secret to orgs

Revision ID: 4487f7bfd011
Revises: 0e0fda40cb5f
Create Date: 2026-04-25 17:02:03.092944
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4487f7bfd011'
down_revision: Union[str, None] = '0e0fda40cb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_secret', sa.String(length=96), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.drop_column('webhook_secret')

    # ### end Alembic commands ###
