"""add email_signature to orgs

Revision ID: a3a1d35ded26
Revises: a59412f81490
Create Date: 2026-04-26 00:54:10.216917
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a3a1d35ded26'
down_revision: Union[str, None] = 'a59412f81490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_signature', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.drop_column('email_signature')

    # ### end Alembic commands ###
