"""add carriers table

Revision ID: a59412f81490
Revises: f0cba7e9af3d
Create Date: 2026-04-26 00:08:43.564262
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a59412f81490'
down_revision: Union[str, None] = 'f0cba7e9af3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carriers_carrier_id'), ['carrier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carriers_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carriers_org_id'))
        batch_op.drop_index(batch_op.f('ix_carriers_carrier_id'))

    op.drop_table('carriers')
    # ### end Alembic commands ###
