"""add notification webhook + draft outcomes

Revision ID: d34018629af0
Revises: f6fb69880057
Create Date: 2026-04-25 15:19:34.539216
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd34018629af0'
down_revision: Union[str, None] = 'f6fb69880057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drafted_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('outcome_set_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('bound_premium_cents', sa.Integer(), nullable=True))

    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_webhook_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.drop_column('notification_webhook_url')

    with op.batch_alter_table('drafted_emails', schema=None) as batch_op:
        batch_op.drop_column('bound_premium_cents')
        batch_op.drop_column('outcome_set_at')
        batch_op.drop_column('outcome')

    # ### end Alembic commands ###
