"""add submission_pdf to triage_runs

Revision ID: f0cba7e9af3d
Revises: 84f96e322c40
Create Date: 2026-04-26 00:01:52.615054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f0cba7e9af3d'
down_revision: Union[str, None] = '84f96e322c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_pdf', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('submission_pdf_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_runs', schema=None) as batch_op:
        batch_op.drop_column('submission_pdf_filename')
        batch_op.drop_column('submission_pdf')

    # ### end Alembic commands ###
