"""initial schema: orgs, triage_runs, appetite_matches, drafted_emails

Revision ID: f6fb69880057
Revises: 
Create Date: 2026-04-25 15:14:04.797830
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f6fb69880057'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('api_key', sa.String(length=96), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('monthly_submission_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orgs_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_orgs_slug'), ['slug'], unique=True)

    op.create_table('triage_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('insured_name', sa.String(length=256), nullable=False),
    sa.Column('primary_state', sa.String(length=8), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('submission_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triage_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triage_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_runs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_runs_submission_id'), ['submission_id'], unique=False)

    op.create_table('appetite_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.String(length=64), nullable=False),
    sa.Column('carrier_name', sa.String(length=256), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('submission_email', sa.String(length=256), nullable=False),
    sa.Column('typical_quote_back_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['triage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appetite_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appetite_matches_run_id'), ['run_id'], unique=False)

    op.create_table('drafted_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.String(length=64), nullable=False),
    sa.Column('to', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=256), nullable=True),
    sa.Column('quote_replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quote_reply_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['triage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafted_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafted_emails_provider_message_id'), ['provider_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafted_emails_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drafted_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafted_emails_run_id'))
        batch_op.drop_index(batch_op.f('ix_drafted_emails_provider_message_id'))

    op.drop_table('drafted_emails')
    with op.batch_alter_table('appetite_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appetite_matches_run_id'))

    op.drop_table('appetite_matches')
    with op.batch_alter_table('triage_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triage_runs_submission_id'))
        batch_op.drop_index(batch_op.f('ix_triage_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_triage_runs_created_at'))

    op.drop_table('triage_runs')
    with op.batch_alter_table('orgs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orgs_slug'))
        batch_op.drop_index(batch_op.f('ix_orgs_api_key'))

    op.drop_table('orgs')
    # ### end Alembic commands ###
